# -*- coding: utf-8 -*-
"""different_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUhs0axg0igngxfVAbqbOKZGkNqvkuaJ
"""

from aiogram import Router, F
from aiogram.types import Message

router = Router()

@router.message(F.document)
async def message_with_doc(message: Message):
    await message.answer("Я не умею работать с документами, мне нужно изображение. Если вы отправили изображение, при повторной отправке нажмите галочку COMPRESS IMAGE")

@router.message(F.video)
async def message_with_video(message: Message):
    await message.answer("Я не умею работать с видео, мне нужно изображение.")

@router.message(F.text)
async def message_with_text(message: Message):
    await message.answer("Я не умею работать с текстом, мне нужно изображение.")

@router.message(F.sticker)
async def message_with_sticker(message: Message):
    await message.answer("Я не умею работать со стикерами, мне нужно изображение.")

@router.message(F.animation)
async def message_with_gif(message: Message):
    await message.answer("Я не умею работать с гифками, мне нужно изображение.")