# -*- coding: utf-8 -*-
"""photo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cgG01paBmQB3x5VPL3-XGDcc6QABLMD
"""

from aiogram import Router, F, Bot
from aiogram.types import Message
import io
from model.prediction import predictions

router = Router()

@router.message(F.photo)
async def download_photo(message: Message, bot: Bot):
   file_in_io = io.BytesIO()
# загружаем фото в папку по умолчанию
   await message.bot.download(file=message.photo[-1],
        destination=file_in_io)
   img_path = file_in_io
# получаем предсказание
   pred = predictions(img_path)
# Отправляем ответ пользователю
   await message.answer(f"Я думаю, что это {pred}")