# -*- coding: utf-8 -*-
"""help_button.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hoT6u3jZk9cu8_EXXU-F0aZDIRVObqY
"""

from aiogram.types import ReplyKeyboardMarkup
from aiogram.utils.keyboard import ReplyKeyboardBuilder

def get_help_kb() -> ReplyKeyboardMarkup:
    kb = ReplyKeyboardBuilder()
    kb.button(text="Помощь")
    return kb.as_markup(resize_keyboard=True)